import React from 'react'

const Terms = () => {
  return (
    <div className='max-w-7xl mx-auto px-12 my-10'>
      <h2 className='text-3xl font-semibold mb-5'>Terms of Use </h2>
      <p>The following terms and conditions govern all use of the ReceiveSMS.co website and all content, services and products available at or through the website. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, ReceiveSMS.co's Privacy Policy) and procedures that may be published from time to time on this Site by ReceiveSMS.co (collectively, the "Agreement").</p>
      <p className='my-3'>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by ReceiveSMS.co, acceptance is expressly limited to these terms.</p>
      <p>ReceiveSMS.co has the right (though not the obligation) to, in ReceiveSMS.co's sole discretion (i) refuse or remove any content that, in ReceiveSMS.co's reasonable opinion, violates any ReceiveSMS.co policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in ReceiveSMS.co's sole discretion. ReceiveSMS.co will have no obligation to provide a refund of any amounts previously paid.</p>
      <p className='my-3'>Termination. ReceiveSMS.co may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your ReceiveSMS.co account (if you have one), you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
      <p>Disclaimer of Warranties. The Website is provided "as is". ReceiveSMS.co and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither ReceiveSMS.co nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</p>
      <p className='my-3'>Limitation of Liability. In no event will ReceiveSMS.co, or its suppliers be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to ReceiveSMS.co under this agreement during the twelve (12) month period prior to the cause of action. ReceiveSMS.co shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law. General Representation and Warranty. You represent and warrant that (i) your use of the Website will be in strict accordance with the ReceiveSMS.co Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party. Indemnification. You agree to indemnify and hold harmless ReceiveSMS.co, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</p>
      <p>Miscellaneous. This Agreement constitutes the entire agreement between ReceiveSMS.co and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of ReceiveSMS.co, or by the posting by ReceiveSMS.co of a revised version. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; ReceiveSMS.co may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.
      </p>
      <p className='my-3'>It is our policy to respect your privacy regarding the use of this service. No personally identifying information is kept, and all message contents are temporary. Your privacy and trust is very important to us. Like most website operators, ReceiveSMS.co collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. ReceiveSMS.co's purpose in collecting non-personally identifying information is to better understand how ReceiveSMS.co's visitors use its website. From time to time, ReceiveSMS.co may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website. ReceiveSMS.co may collect statistics about the behavior of visitors to its websites. ReceiveSMS.co may display this information publicly or provide it to others. However, ReceiveSMS.co does not collect or disclose personally-identifying information other than as described below. Google is used as an advertisement vendor and employs cookies to serve ads on this site. ReceiveSMS.co has no access to the cookies used by Google or other advertising vendors for the serving of these advertisements.</p>
    </div>
  )
}

export default Terms